<?xml version="1.0" ?>
<robot name="ur5" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
    <xacro:include filename="$(find ur_description)/urdf/ur5camera.gazebo.xacro" />
<xacro:property name="camera_link" value="0.005" />
<xacro:property name="height3" value="0.1" />
 <xacro:property name="axel_offset" value="0.005" /> <!-- Space btw top of beam and the each joint -->

<!--  <xacro:include filename="$(find ur_description)/urdf/ur.gazebo.xacro" />-->

<xacro:ur5_robot prefix="" joint_limited="true"/>
<link name="world" />

<joint name="world_joint" type="fixed">
   <parent link="world" />
   <child link = "base_link" />
   <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
 </joint>

<joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="ee_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
      </material>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
</robot>
